
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0

name: Release
permissions:
  contents: write

jobs:
  crate_publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@ed2356ad628626a6b3f5be6c3e0255c0454fcdb9

      - name: Run tests
        run: cargo login $CARGO_TOKEN
        env:
          CARGO_TOKEN: ${{secrets.CARGO_TOKEN}}

      - name: Run publish
        run: cargo publish
 
  release_linux:
    name: Release (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@ed2356ad628626a6b3f5be6c3e0255c0454fcdb9

      - name: Run cargo build
        run: cargo build --all --release

      - name: Strip and rename binary
        run: strip target/release/dirqd && mv target/release/dirqd target/release/dirqd_linux_amd64

      - name: Release
        uses: softprops/action-gh-release@9a28f2423fd7ba2781181bb13e8aba228027c4e9
        with:
          files: |
            target/release/dirqd_linux_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_windows:
    name: Release (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@ed2356ad628626a6b3f5be6c3e0255c0454fcdb9

      - name: Run cargo build
        run: cargo build --all --release

      - name: Rename binary
        run: ren target/release/dirqd.exe dirqd_windows_amd64.exe

      - name: Release
        uses: softprops/action-gh-release@9a28f2423fd7ba2781181bb13e8aba228027c4e9
        with:
          files: |
            target/release/dirqd_windows_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_macos:
    name: Release (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@ed2356ad628626a6b3f5be6c3e0255c0454fcdb9

      - name: Run cargo build
        run: cargo build --all --release

      - name: Strip and rename binary
        run: strip target/release/dirqd && mv target/release/dirqd target/release/dirqd_macos_amd64

      - name: Release
        uses: softprops/action-gh-release@9a28f2423fd7ba2781181bb13e8aba228027c4e9
        with:
          files: |
            target/release/dirqd_macos_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
